# Generated by Django 4.2.5 on 2023-10-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dp_link',
            field=models.URLField(default=None, null=True),
        ),
    ]
