# Generated by Django 4.2.5 on 2023-09-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='can_delete',
            field=models.BooleanField(default=True),
        ),
    ]
