# Generated by Django 4.2.5 on 2023-10-22 10:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_list', '0003_todolist_can_delete'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='todolist',
            unique_together={('title', 'owner')},
        ),
    ]
