# Generated by Django 4.2.5 on 2023-09-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_item', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=50),
        ),
    ]
